#!/bin/bash
if [ $# -lt 2 ]; then 
	echo -e "scancode: a simple tool to scan codebases to find variables or functions based on their name\nusage:\nscancode file_extension(dont put a dot) function_name/variable_name\nscancode file_extension(dont put a dot) function_name/variable_name --dont-ignore-case"
elif [ $# -eq 2 ];then
	for i in `find ./ -iname *.$1`;do if [ -z "$(cat $i|grep -i $2)" ];then echo -n "";else echo "in $i:";cat -n $i|grep -i $2;fi;done|less
else
	for i in `find ./ -iname *.$1`;do if [ -z "$(cat $i|grep $2)" ];then echo -n "";else echo "in $i:";cat -n $i|grep $2;fi;done|less
fi
